title: 
  Dataset on the Global Network of Liquidity Lines
description: >- # this means to ignore newlines until "baseurl:"
 Download the dataset and reproduce some of the figures
baseurl: 
  "/web-lines" # the subpath of your site, e.g. /blog
url: 
  "https://R2RsquaredLSE.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  
  R2RsquaredLSE

# Build settings
theme: jekyll-theme-cayman
